//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOWA_ITA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maullin.sii.cl/DTEWS/QueryEstDte.jws")]
        public string BOWA_ITA_Certificacion_EstadoDTE_QueryEstDteService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_EstadoDTE_QueryEstDteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maullin.sii.cl/DTEWS/services/QueryEstDteAv")]
        public string BOWA_ITA_Certificacion_EstadoDTEAvanzado_QueryEstDteAvService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_EstadoDTEAvanzado_QueryEstDteAvService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maullin.sii.cl/DTEWS/QueryEstUp.jws")]
        public string BOWA_ITA_Certificacion_EstadoEnvio_QueryEstUpService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_EstadoEnvio_QueryEstUpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws2.sii.cl/WSREGISTRORECLAMODTECERT/registroreclamodteservice")]
        public string BOWA_ITA_Certificacion_RegistroReclamoWS_RegistroReclamoDteServiceEndpointService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_RegistroReclamoWS_RegistroReclamoDteServiceEndpointService" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maullin.sii.cl/DTEWS/CrSeed.jws")]
        public string BOWA_ITA_Certificacion_Seed_CrSeedService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_Seed_CrSeedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maullin.sii.cl/DTEWS/GetTokenFromSeed.jws")]
        public string BOWA_ITA_Certificacion_Token_GetTokenFromSeedService {
            get {
                return ((string)(this["BOWA_ITA_Certificacion_Token_GetTokenFromSeedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/QueryEstDte.jws")]
        public string BOWA_ITA_Produccion_EstadoDTE_QueryEstDteService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_EstadoDTE_QueryEstDteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/services/QueryEstDteAv")]
        public string BOWA_ITA_Produccion_EstadoDTEAvanzado_QueryEstDteAvService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_EstadoDTEAvanzado_QueryEstDteAvService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/QueryEstUp.jws")]
        public string BOWA_ITA_Produccion_EstadoEnvio_QueryEstUpService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_EstadoEnvio_QueryEstUpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws1.sii.cl/WSREGISTRORECLAMODTE/registroreclamodteservice")]
        public string BOWA_ITA_Produccion_RegistroReclamo_RegistroReclamoDteServiceEndpointService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_RegistroReclamo_RegistroReclamoDteServiceEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/CrSeed.jws")]
        public string BOWA_ITA_Produccion_Seed_CrSeedService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_Seed_CrSeedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/GetTokenFromSeed.jws")]
        public string BOWA_ITA_Produccion_Token_GetTokenFromSeedService {
            get {
                return ((string)(this["BOWA_ITA_Produccion_Token_GetTokenFromSeedService"]));
            }
        }
    }
}
